-- no duplicates, average, row count
DELETE FROM CHECK_OBJECT;
INSERT INTO CHECK_OBJECT(LOAD_DATE, INT_VALUE, FLOAT_VALUE, CHAR_VALUE, DATE_VALUE)
VALUES(CURDATE(), 2, 3.28, 'B', CURDATE()),
(CURDATE(), 4, 6.3, 'С', CURDATE()),
(CURDATE(), 2, 1.24, 'С', CURDATE()),
(CURDATE()-1, 42, 63.33, 'f', CURDATE());