-- null count
DELETE FROM CHECK_OBJECT;
INSERT INTO CHECK_OBJECT(LOAD_DATE, INT_VALUE, FLOAT_VALUE, CHAR_VALUE, DATE_VALUE)
VALUES(CURDATE(), NULL, NULL, NULL, CURDATE()),
(CURDATE(), 1, NULL, 'С', NULL),
(CURDATE(), NULL, NULL, 'DF', CURDATE()-2);