-- zeros count
DELETE FROM CHECK_OBJECT;
INSERT INTO CHECK_OBJECT(LOAD_DATE, INT_VALUE, FLOAT_VALUE, CHAR_VALUE, DATE_VALUE)
VALUES(CURDATE(), 0, 2.2, 'TEST', CURDATE()),
(CURDATE(), 1, 0.0, 'С', CURDATE()-3),
(CURDATE(), 12, 0.0, 'DF', CURDATE()-2)